language: node_js
cache:
  directories:
    - ~/.npm
    - ~/node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_script:
  - yarn install
script:
  - npm test
  - npm run check-coverage
  - npm run build
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - next
  except:
    - /^v\d+\.\d+\.\d+$/
